# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RoverUI_imu.ui'
#
# Created: Fri Mar 13 19:59:43 2015
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(583, 348)
        self.gridLayout_5 = QtGui.QGridLayout(Dialog)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_quat = QtGui.QLabel(Dialog)
        self.label_quat.setObjectName(_fromUtf8("label_quat"))
        self.verticalLayout.addWidget(self.label_quat)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit_Quat_x = QtGui.QLineEdit(Dialog)
        self.lineEdit_Quat_x.setReadOnly(True)
        self.lineEdit_Quat_x.setObjectName(_fromUtf8("lineEdit_Quat_x"))
        self.horizontalLayout.addWidget(self.lineEdit_Quat_x)
        self.lineEdit_Quat_y = QtGui.QLineEdit(Dialog)
        self.lineEdit_Quat_y.setReadOnly(True)
        self.lineEdit_Quat_y.setObjectName(_fromUtf8("lineEdit_Quat_y"))
        self.horizontalLayout.addWidget(self.lineEdit_Quat_y)
        self.lineEdit_Quat_z = QtGui.QLineEdit(Dialog)
        self.lineEdit_Quat_z.setReadOnly(True)
        self.lineEdit_Quat_z.setObjectName(_fromUtf8("lineEdit_Quat_z"))
        self.horizontalLayout.addWidget(self.lineEdit_Quat_z)
        self.lineEdit_Quat_w = QtGui.QLineEdit(Dialog)
        self.lineEdit_Quat_w.setReadOnly(True)
        self.lineEdit_Quat_w.setObjectName(_fromUtf8("lineEdit_Quat_w"))
        self.horizontalLayout.addWidget(self.lineEdit_Quat_w)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 4)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_angV = QtGui.QLabel(Dialog)
        self.label_angV.setObjectName(_fromUtf8("label_angV"))
        self.verticalLayout_2.addWidget(self.label_angV)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit_AV_z = QtGui.QLineEdit(Dialog)
        self.lineEdit_AV_z.setReadOnly(True)
        self.lineEdit_AV_z.setObjectName(_fromUtf8("lineEdit_AV_z"))
        self.gridLayout_2.addWidget(self.lineEdit_AV_z, 0, 2, 1, 1)
        self.lineEdit_AV_y = QtGui.QLineEdit(Dialog)
        self.lineEdit_AV_y.setReadOnly(True)
        self.lineEdit_AV_y.setObjectName(_fromUtf8("lineEdit_AV_y"))
        self.gridLayout_2.addWidget(self.lineEdit_AV_y, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 2, 1, 1)
        self.lineEdit_AV_x = QtGui.QLineEdit(Dialog)
        self.lineEdit_AV_x.setReadOnly(True)
        self.lineEdit_AV_x.setObjectName(_fromUtf8("lineEdit_AV_x"))
        self.gridLayout_2.addWidget(self.lineEdit_AV_x, 0, 0, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_linA = QtGui.QLabel(Dialog)
        self.label_linA.setObjectName(_fromUtf8("label_linA"))
        self.verticalLayout_3.addWidget(self.label_linA)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 2, 1, 1)
        self.lineEdit_LA_z = QtGui.QLineEdit(Dialog)
        self.lineEdit_LA_z.setReadOnly(True)
        self.lineEdit_LA_z.setObjectName(_fromUtf8("lineEdit_LA_z"))
        self.gridLayout_3.addWidget(self.lineEdit_LA_z, 0, 2, 1, 1)
        self.lineEdit_LA_y = QtGui.QLineEdit(Dialog)
        self.lineEdit_LA_y.setReadOnly(True)
        self.lineEdit_LA_y.setObjectName(_fromUtf8("lineEdit_LA_y"))
        self.gridLayout_3.addWidget(self.lineEdit_LA_y, 0, 1, 1, 1)
        self.lineEdit_LA_x = QtGui.QLineEdit(Dialog)
        self.lineEdit_LA_x.setReadOnly(True)
        self.lineEdit_LA_x.setObjectName(_fromUtf8("lineEdit_LA_x"))
        self.gridLayout_3.addWidget(self.lineEdit_LA_x, 0, 0, 1, 1)
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_linA_2 = QtGui.QLabel(Dialog)
        self.label_linA_2.setObjectName(_fromUtf8("label_linA_2"))
        self.verticalLayout_4.addWidget(self.label_linA_2)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_11 = QtGui.QLabel(Dialog)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(Dialog)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 1, 2, 1, 1)
        self.lineEdit_Euler_yaw = QtGui.QLineEdit(Dialog)
        self.lineEdit_Euler_yaw.setReadOnly(True)
        self.lineEdit_Euler_yaw.setObjectName(_fromUtf8("lineEdit_Euler_yaw"))
        self.gridLayout_4.addWidget(self.lineEdit_Euler_yaw, 0, 2, 1, 1)
        self.lineEdit_Euler_pitch = QtGui.QLineEdit(Dialog)
        self.lineEdit_Euler_pitch.setReadOnly(True)
        self.lineEdit_Euler_pitch.setObjectName(_fromUtf8("lineEdit_Euler_pitch"))
        self.gridLayout_4.addWidget(self.lineEdit_Euler_pitch, 0, 1, 1, 1)
        self.lineEdit_Euler_roll = QtGui.QLineEdit(Dialog)
        self.lineEdit_Euler_roll.setReadOnly(True)
        self.lineEdit_Euler_roll.setObjectName(_fromUtf8("lineEdit_Euler_roll"))
        self.gridLayout_4.addWidget(self.lineEdit_Euler_roll, 0, 0, 1, 1)
        self.label_13 = QtGui.QLabel(Dialog)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_4)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "IMU Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label_quat.setText(QtGui.QApplication.translate("Dialog", "Quaternion Orientation Values", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "w", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_angV.setText(QtGui.QApplication.translate("Dialog", "Angular Velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_linA.setText(QtGui.QApplication.translate("Dialog", "Linear Acceleration", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_linA_2.setText(QtGui.QApplication.translate("Dialog", "Euler Angles", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "roll", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "yaw", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "pitch", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

