/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/marsrover/Documents/uwrobotics.uwmrt/Software/Workspace/src/joystick_packages/msg/JoystickMsg.msg
 *
 */


#ifndef JOYSTICK_PACKAGES_MESSAGE_JOYSTICKMSG_H
#define JOYSTICK_PACKAGES_MESSAGE_JOYSTICKMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace joystick_packages
{
template <class ContainerAllocator>
struct JoystickMsg_
{
  typedef JoystickMsg_<ContainerAllocator> Type;

  JoystickMsg_()
    : type(0)
    , number(0)
    , value(0)  {
    }
  JoystickMsg_(const ContainerAllocator& _alloc)
    : type(0)
    , number(0)
    , value(0)  {
    }



   typedef int8_t _type_type;
  _type_type type;

   typedef int8_t _number_type;
  _number_type number;

   typedef int8_t _value_type;
  _value_type value;




  typedef boost::shared_ptr< ::joystick_packages::JoystickMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::joystick_packages::JoystickMsg_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct JoystickMsg_

typedef ::joystick_packages::JoystickMsg_<std::allocator<void> > JoystickMsg;

typedef boost::shared_ptr< ::joystick_packages::JoystickMsg > JoystickMsgPtr;
typedef boost::shared_ptr< ::joystick_packages::JoystickMsg const> JoystickMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::joystick_packages::JoystickMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::joystick_packages::JoystickMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace joystick_packages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'joystick_packages': ['/home/marsrover/Documents/uwrobotics.uwmrt/Software/Workspace/src/joystick_packages/msg'], 'std_msgs': ['/opt/ros/hydro/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::joystick_packages::JoystickMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::joystick_packages::JoystickMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joystick_packages::JoystickMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joystick_packages::JoystickMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joystick_packages::JoystickMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joystick_packages::JoystickMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::joystick_packages::JoystickMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d852a84dd4742fd04b95b69c878d3172";
  }

  static const char* value(const ::joystick_packages::JoystickMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd852a84dd4742fd0ULL;
  static const uint64_t static_value2 = 0x4b95b69c878d3172ULL;
};

template<class ContainerAllocator>
struct DataType< ::joystick_packages::JoystickMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "joystick_packages/JoystickMsg";
  }

  static const char* value(const ::joystick_packages::JoystickMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::joystick_packages::JoystickMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 type\n\
int8 number\n\
int8 value\n\
";
  }

  static const char* value(const ::joystick_packages::JoystickMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::joystick_packages::JoystickMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.number);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct JoystickMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::joystick_packages::JoystickMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::joystick_packages::JoystickMsg_<ContainerAllocator>& v)
  {
    s << indent << "type: ";
    Printer<int8_t>::stream(s, indent + "  ", v.type);
    s << indent << "number: ";
    Printer<int8_t>::stream(s, indent + "  ", v.number);
    s << indent << "value: ";
    Printer<int8_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JOYSTICK_PACKAGES_MESSAGE_JOYSTICKMSG_H
